version: 0.2

phases:
  install:
    commands:
      - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.23.0/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv -f ./kubectl /usr/local/bin/kubectl
  pre_build:
    commands:
      - echo Logging in to AWS EKS...
      - aws eks update-kubeconfig --region us-east-1 --name cluster-aula-cesar
  post_build:
    commands:
      - echo Instalando...
      - aws sts get-caller-identity
      - kubectl apply -f kubernetes/